"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


def get_env_setting(key: str, default=None, required: bool = False):
    value = os.getenv(key, default)
    if required and value is None:
        raise ImproperlyConfigured(f"Set the {key} environment variable")
    return value


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_env_setting("DJANGO_SECRET_KEY", required=True)


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_env_setting("DJANGO_DEBUG", "True").lower() in ("true", "1", "yes", "on")

ALLOWED_HOSTS = [
    host.strip()
    for host in get_env_setting("DJANGO_ALLOWED_HOSTS", "").split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'daphne',
    'corsheaders',
    'django_celery_beat',
    'django.contrib.sites',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'base.apps.BaseConfig',
    'base.tasks',
    'django_celery_results',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION = "core.asgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': get_env_setting("POSTGRES_DB", "ChatApp"),
        'USER': get_env_setting("POSTGRES_USER", "postgres"),
        'PASSWORD': get_env_setting("POSTGRES_PASSWORD", "1234"),
        'HOST': get_env_setting("POSTGRES_HOST", "localhost"),
        'PORT': get_env_setting("POSTGRES_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'  
MEDIA_ROOT = BASE_DIR/'media'

STATICFILES_DIRS=(BASE_DIR/'static',)

# CORS_ALLOWED_ORIGINS=[
#     "http://localhost:5137"
# ]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True


REDIS_HOST = get_env_setting("REDIS_HOST", "127.0.0.1")
REDIS_PORT = int(get_env_setting("REDIS_PORT", "6379"))
REDIS_URL = get_env_setting("REDIS_URL", f"redis://{REDIS_HOST}:{REDIS_PORT}/0")

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(REDIS_HOST, REDIS_PORT)],
        },
    }
}

CELERY_BROKER_URL = get_env_setting("CELERY_BROKER_URL", REDIS_URL)
CELERY_TIMEZONE = "Asia/Kolkata"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60

# "redis://localhost:6379/0"
CELERY_RESULT_BACKEND = get_env_setting("CELERY_RESULT_BACKEND", "django-db")

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 5
}

SITE_BASE_URL = get_env_setting("SITE_BASE_URL")
LLM_BASE_URL = get_env_setting("LLM_BASE_URL", "http://127.0.0.1:1239/v1/")
LLM_MODEL_NAME = get_env_setting("LLM_MODEL_NAME", "hermes-3-llama-3.2-3b")
LLM_API_KEY = get_env_setting("LLM_API_KEY", "lm_studio")
CHROMA_HOST = get_env_setting("CHROMA_HOST", "localhost")
CHROMA_PORT = int(get_env_setting("CHROMA_PORT", "3000"))