# Generated by Django 5.2.6 on 2025-09-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField()),
                ('bio', models.TextField()),
                ('last_seen', models.DateField(auto_now=True)),
                ('is_online', models.BooleanField(default=False)),
                ('profile_pic', models.ImageField(upload_to='avatars/')),
                ('roles', models.CharField(choices=[('admin', 'Admin'), ('User', 'user'), ('Moderator', 'moderator')], max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
