# Generated by Django 5.2.6 on 2025-11-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_pollvote_poll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='choices',
            field=models.JSONField(default=dict),
        ),
    ]
