# Generated by Django 5.2.6 on 2025-11-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_poll_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollvote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
