# Generated by Django 5.2.6 on 2025-09-30 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_user_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_seen',
            field=models.DateField(default=datetime.datetime(2025, 9, 30, 18, 19, 50, 615571, tzinfo=datetime.timezone.utc)),
        ),
    ]
