# Generated by Django 5.2.6 on 2025-10-07 06:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_emoji_message_reaction_room_topic_userprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='memeber',
            field=models.ManyToManyField(blank=True, null=True, related_name='room_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
