# Generated by Django 5.2.6 on 2025-11-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_pollvote_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
