# Generated by Django 5.2.6 on 2025-11-02 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_poll_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatFileLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastSummerized', models.DateTimeField(auto_now=True)),
                ('fileLocation', models.FileField(upload_to='')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.room')),
            ],
        ),
        migrations.CreateModel(
            name='MessageSummerizedStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.message')),
            ],
        ),
    ]
