# Generated by Django 5.2.6 on 2025-09-30 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_user_last_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField()),
                ('bio', models.TextField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(default=datetime.datetime(2025, 9, 30, 19, 2, 35, 39038, tzinfo=datetime.timezone.utc))),
                ('is_online', models.BooleanField(default=False)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('roles', models.CharField(choices=[('admin', 'Admin'), ('User', 'user'), ('Moderator', 'moderator')], max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
