# Generated by Django 5.2.6 on 2025-09-30 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_userprofile_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 30, 19, 6, 19, 526032, tzinfo=datetime.timezone.utc)),
        ),
    ]
