# Generated by Django 5.2.6 on 2025-11-03 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_chatfilelog_messagesummerizedstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesummerizedstatus',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.message'),
        ),
    ]
