# Generated by Django 5.2.6 on 2025-11-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_messagesummerizedstatus_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='tags',
            field=models.JSONField(default=dict),
        ),
    ]
