# Generated by Django 5.2.6 on 2025-10-08 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_room_members_alter_room_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='participants',
        ),
    ]
