# Generated by Django 5.2.6 on 2025-10-01 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_userprofile_last_seen_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 1, 15, 31, 2, 68932, tzinfo=datetime.timezone.utc)),
        ),
    ]
