# Generated by Django 5.2.6 on 2025-11-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_notification'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('room', 'message'), name='unique_message_room_notification'),
        ),
    ]
