# Generated by Django 5.2.6 on 2025-10-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='rooms_visited',
            field=models.JSONField(null=True),
        ),
    ]
