# Generated by Django 5.2.6 on 2025-10-10 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_history_rooms_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='session',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='time_spent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='rooms_visited',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_history', to='base.room'),
        ),
    ]
