# Generated by Django 5.2.6 on 2025-10-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_message_reaction_message_reactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(default='no msg'),
        ),
    ]
