# Generated by Django 5.2.6 on 2025-10-12 07:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_history_session_history_time_spent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='moderator',
            field=models.ManyToManyField(default='self', related_name='room_moderator', to=settings.AUTH_USER_MODEL),
        ),
    ]
