# Generated by Django 5.2.6 on 2025-10-12 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_room_moderator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='moderator',
            field=models.ManyToManyField(related_name='room_moderator', to=settings.AUTH_USER_MODEL),
        ),
    ]
