# Generated by Django 5.2.6 on 2025-10-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_room_moderator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='reactions',
        ),
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
