# Generated by Django 5.2.6 on 2025-10-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_message_reactions_message_file_message_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='vote',
            field=models.SmallIntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')], default=0),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
