# Generated by Django 5.2.6 on 2025-10-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_message_vote_delete_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
        migrations.AddField(
            model_name='message',
            name='file_msg',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='message',
            name='images_msg',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
